# prod-account-roles.yaml

Resources:
  VPCFlowLogsRoleProd:
    Type: AWS::IAM::Role
    Properties:
      RoleName: VPCFlowLogsRoleProd
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: vpc-flow-logs.amazonaws.com
            Action: sts:AssumeRole

  AssumeVPCFlowLogsRolePolicyProd:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: AssumeVPCFlowLogsRole
      Roles:
        - Ref: VPCFlowLogsRoleProd
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action: sts:AssumeRole
            Resource: arn:aws:iam::615299757391:role/VPCFlowLogsRoleProd
      Tags:
        - Key: account
          Value: prod
        - Key: project
          Value: project9
        - Key: owner
          Value: ykudaibergen
        - Key: team
          Value: cat
        - Key: purpose
          Value: VPCFlowLogsToAssumeRole
